dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: praticas-dbt
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_dw') }}"
      threads: 4
      keyfile: /home/danielpedro/Engenharia de Dados/dbt_estudos/praticas-dbt-5f6ada57c89a.json